### ISSUE TITLE
Organization of Preferences

### ISSUE THREAD

**Issue by iangreenleaf** [grinnellplans/GrinnellPlans#23]
There's no reason we need to preserve the exact organization of the current preferences. Two things that would be helpful:

 * Decide which options should be grouped together on pages
 * Decide how the main Preferences page should be laid out and what the links should say

**Comment by ghadirim** [comment]
Here's what I'm thinking: 

Main screen: Preferences 

1. account information
subgroup 1 for name/password/permanent email (account information)
subgroup 2  optional links

2. Privacy 
subgroup 1. guest readable 
subgroup 2. blocking feature

3. Customize your page
subgroup 1 style sheets (link to [css] on same page?)
Do people mess with the size of the text box? Does this need to be an option? I never do.

I would like to add a feature showing all the people you follow and on what level so you can edit/change in one go. One of the reasons I don't use the levels is because I have no idea who is under which one so I just have everyone under level 1. 

on another note, I never really understood the behind the scenes on this, but can we push everyone to postmodern interface and take away the option to be anything else? Is there a benefit to the other ones?

**Comment by iangreenleaf** [comment]
Mona, thanks! That sounds like a good organization to me. When you say "subgroup" are you thinking sections within a page? We can probably give them a border and subheadings to make it more obvious.

>  Do people mess with the size of the text box? Does this need to be an option? I never do.

We decided that no, it doesn't need to be an option (#26), and are planning to look into making it sane defaults instead (#83).

> I would like to add a feature showing all the people you follow and on what level so you can edit/change in one go.

Oh yeah, me too. With some drag 'n' drop, and the ability to add and rename levels? That would be great, and something I'll definitely have in mind as a post-launch task.

> on another note, I never really understood the behind the scenes on this, but can we push everyone to postmodern interface and take away the option to be anything else? Is there a benefit to the other ones?

Yes, we're hoping to do that (implementing other interfaces would be a huge nuisance as we do this rewrite). @baldwint has already done some fantastic work porting (I think) all the default stylesheets to postmodern, so we can switch over to those and most people won't notice a difference. There will be a small number of people using custom stylesheets based on the old interfaces who will have things break, which is regrettable but probably a price worth paying. Opening #92 to track this.

**Comment by ghadirim** [comment]
Yes, exactly. Sections within a page. I think with border and subheading it should be pretty obvious. Thanks for requesting input!

**Comment by iangreenleaf** [comment]
Broke this out into sections to implement each of the pages, closing.
