### ISSUE TITLE
Drop old interfaces and migrate CSS

### ISSUE THREAD

**Issue by iangreenleaf** [grinnellplans/GrinnellPlans#92]
A lot of work has already occurred on this, but it doesn't have a ticket open yet. In short, we plan to drop support for the older interfaces and use something resembling Postmodern for all users. @baldwint put in a Herculean effort porting most or all of the standard stylesheet options to work with this new interface, so we can migrate everyone who's using those. Then the only drawback is that anyone using a custom stylesheet that depends on the old interfaces will have it break, which hopefully we can minimize.

* [x] Finish porting standard stylesheets
* [ ] Make [base stylesheet](https://github.com/baldwint/planscss/blob/css/html/styles/modern.css) readily available + instructions for using it
* [ ] Compile list of [stylesheets in use and dependent on old interfaces](https://groups.google.com/forum/#!topic/grinnellplans-development/jtgwbmNlWdI)
* [ ] Reach out to those authors and see if we can get them to update.

**Comment by iangreenleaf** [comment]
@baldwint, could you clarify for me how far the CS porting is? Blue, Jolly and Parchment are not yet ported, is that correct? And is all of your work found in https://github.com/baldwint/planscss ?

**Comment by baldwint** [comment]
The CSS porting is complete for every built-in stylesheet. Yes, all my work is in the repo you linked, but **not in branch master**. The new sheets are in the `css` branch (I used `master` exclusively to code up a preview tool in PhantomJS).

This work was committed to PHP Plans in a [single giant patch](https://github.com/grinnellplans/grinnellplans-php/commit/4512e3f39eb0abe199f4d1f676bfdabb9640ebbf) on March 15. It was partially reverted [a month later](https://github.com/grinnellplans/grinnellplans-php/commit/2ad3d2b587112fed103cb924408981218bb4c73a) because someone really hated having the pre-2009 plans logos back. I think it must have been a younger person who didn't know that those were *original*, *vintage* logos, painstakingly recovered from the dank depths of the SVN repo. Anyway if you share that person's opinion you should pull from the `nologos` branch instead (check the [network graph](https://github.com/baldwint/planscss/network)).

I don't have much time to work on plans these days but I hope this helps you guys.

**Comment by iangreenleaf** [comment]
@baldwint thank you, that was exactly the information I needed. I'll pull in all your latest sheets, and uhhhhh we'll see about those vintage logos.

**Comment by iangreenleaf** [comment]
I'm going to break out further work on this into tickets under a new milestone: #139 and #140.
